export type Estatus =
  | 'Nuevo'
  | 'Pendiente'
  | 'PENDIENTE'
  | 'En proceso'
  | 'EN PROCESO'
  | 'Cotizado'
  | 'COTIZADO'
  | 'Confirmada'
  | 'CONFIRMADA'
  | 'Cerrado'
  | 'CERRADO'
  | 'Cancelado'
  | 'CANCELADO'
  | 'SUMINISTRADA'
  | 'ALMACENADA'
  | 'RECOLECTADA'
  | 'UTILIZADA'
  | 'DEVUELTA'
  | 'EN BODEGA'
  | 'DESTRUIDA'
  | 'BOLETINADA'
  | 'INACTIVO'
  | 'APLICADO'
  | 'CONSIGNADA'
  | 'ASIGNADA'
  | 'ACTIVO';
