-- Fichas públicas administrables. Los textos visibles se traducen por idioma;
-- las fechas, importes y relaciones se mantienen como datos independientes.
create table public.cabanas (
  id bigint generated by default as identity primary key,
  catalogo_destino_id bigint not null references public.catalogo_destinos(id),
  zona text,
  imagen_principal text not null,
  precio_desde numeric(12,2) not null check (precio_desde >= 0),
  moneda text not null default 'MXN' check (moneda ~ '^[A-Z]{3}$'),
  precio_por text not null check (precio_por in ('noche', 'estancia')),
  precio_personas integer not null check (precio_personas > 0),
  adultos_max integer not null check (adultos_max > 0),
  ninos_max integer not null default 0 check (ninos_max >= 0),
  habitaciones integer not null check (habitaciones > 0),
  disponible_desde date,
  disponible_hasta date,
  referencia_mapa text,
  publicada boolean not null default false,
  created_at timestamptz not null default now(),
  check (disponible_hasta is null or disponible_desde is null or disponible_hasta >= disponible_desde)
);
create index cabanas_destino_idx on public.cabanas(catalogo_destino_id);

create table public.cabanas_traducciones (
  cabana_id bigint not null references public.cabanas(id) on delete cascade,
  idioma_id bigint not null references public.idiomas(id),
  nombre text not null,
  descripcion text not null default '',
  camas text not null default '',
  experiencia text not null default '',
  zona text not null default '',
  referencia_mapa text not null default '',
  primary key (cabana_id, idioma_id)
);
create table public.cabanas_imagenes (
  id bigint generated by default as identity primary key,
  cabana_id bigint not null references public.cabanas(id) on delete cascade,
  url text not null,
  orden integer not null default 0
);
create index cabanas_imagenes_orden_idx on public.cabanas_imagenes(cabana_id, orden);
create table public.cabanas_amenidades (
  cabana_id bigint not null references public.cabanas(id) on delete cascade,
  actividad_id bigint not null references public.actividades(id),
  primary key (cabana_id, actividad_id)
);

create table public.promociones (
  id bigint generated by default as identity primary key,
  hotel_id bigint references public.hoteles(id),
  catalogo_destino_id bigint references public.catalogo_destinos(id),
  imagen_principal text not null,
  precio_promocional numeric(12,2) check (precio_promocional >= 0),
  precio_anterior numeric(12,2) check (precio_anterior >= 0),
  descuento_porcentaje numeric(5,2) check (descuento_porcentaje > 0 and descuento_porcentaje <= 100),
  moneda text not null default 'MXN' check (moneda ~ '^[A-Z]{3}$'),
  vigencia_desde date not null,
  vigencia_hasta date not null,
  viaje_desde date not null,
  viaje_hasta date not null,
  publicada boolean not null default false,
  created_at timestamptz not null default now(),
  check (hotel_id is not null or catalogo_destino_id is not null),
  check (vigencia_hasta >= vigencia_desde and viaje_hasta >= viaje_desde),
  check (precio_promocional is not null or descuento_porcentaje is not null),
  check (precio_anterior is null or precio_promocional is null or precio_anterior > precio_promocional)
);
create index promociones_vigencia_idx on public.promociones(publicada, vigencia_desde, vigencia_hasta);
create table public.promociones_traducciones (
  promocion_id bigint not null references public.promociones(id) on delete cascade,
  idioma_id bigint not null references public.idiomas(id),
  titulo text not null,
  etiqueta text not null default '',
  condiciones text not null default '',
  primary key (promocion_id, idioma_id)
);

-- La lectura anónima nunca expone borradores, ni siquiera en tablas hijas.
alter table public.cabanas enable row level security;
alter table public.cabanas_traducciones enable row level security;
alter table public.cabanas_imagenes enable row level security;
alter table public.cabanas_amenidades enable row level security;
alter table public.promociones enable row level security;
alter table public.promociones_traducciones enable row level security;

grant select on public.cabanas, public.cabanas_traducciones, public.cabanas_imagenes, public.cabanas_amenidades, public.promociones, public.promociones_traducciones to anon, authenticated;
grant insert, update, delete on public.cabanas, public.cabanas_traducciones, public.cabanas_imagenes, public.cabanas_amenidades, public.promociones, public.promociones_traducciones to authenticated;
grant usage, select on sequence public.cabanas_id_seq, public.cabanas_imagenes_id_seq, public.promociones_id_seq to authenticated;

create policy cabanas_select on public.cabanas for select using (
  publicada or exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin')
);
create policy promociones_select on public.promociones for select using (
  (publicada and current_date between vigencia_desde and vigencia_hasta)
  or exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin')
);
create policy cabanas_traducciones_select on public.cabanas_traducciones for select using (
  exists (select 1 from public.cabanas c where c.id = cabana_id)
);
create policy cabanas_imagenes_select on public.cabanas_imagenes for select using (
  exists (select 1 from public.cabanas c where c.id = cabana_id)
);
create policy cabanas_amenidades_select on public.cabanas_amenidades for select using (
  exists (select 1 from public.cabanas c where c.id = cabana_id)
);
create policy promociones_traducciones_select on public.promociones_traducciones for select using (
  exists (select 1 from public.promociones p where p.id = promocion_id)
);

-- Escritura exclusiva para administradores, incluso para las relaciones hijas.
create policy cabanas_insert on public.cabanas for insert to authenticated with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
create policy cabanas_update on public.cabanas for update to authenticated using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin')) with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
create policy cabanas_delete on public.cabanas for delete to authenticated using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
create policy promociones_insert on public.promociones for insert to authenticated with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
create policy promociones_update on public.promociones for update to authenticated using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin')) with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
create policy promociones_delete on public.promociones for delete to authenticated using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));

create policy cabanas_traducciones_write on public.cabanas_traducciones for all to authenticated using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin')) with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
create policy cabanas_imagenes_write on public.cabanas_imagenes for all to authenticated using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin')) with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
create policy cabanas_amenidades_write on public.cabanas_amenidades for all to authenticated using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin')) with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
create policy promociones_traducciones_write on public.promociones_traducciones for all to authenticated using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin')) with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'));
