create table if not exists public.atracciones_carpetas (
  id bigint generated by default as identity primary key,
  atraccion_id bigint not null references public.atracciones_principales(id) on delete cascade,
  nombre text not null,
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.atracciones_carpetas
  add constraint atracciones_carpetas_unica_por_atraccion_nombre unique (atraccion_id, nombre);

create index if not exists atracciones_carpetas_atraccion_orden_idx
  on public.atracciones_carpetas (atraccion_id, orden, id);

alter table if exists public.atracciones_imagenes
  add column if not exists carpeta_id bigint null;

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'atracciones_imagenes'
      and constraint_name = 'atracciones_imagenes_carpeta_id_fkey'
  ) then
    alter table public.atracciones_imagenes
      add constraint atracciones_imagenes_carpeta_id_fkey
      foreign key (carpeta_id)
      references public.atracciones_carpetas (id)
      on delete set null;
  end if;
end $$;

insert into public.atracciones_carpetas (atraccion_id, nombre, orden)
select
  base.atraccion_id,
  base.nombre,
  row_number() over (
    partition by base.atraccion_id
    order by base.nombre
  ) as orden
from (
  select distinct
    ai.atraccion_id,
    coalesce(nullif(trim(ai.carpeta), ''), 'Sin carpeta') as nombre
  from public.atracciones_imagenes ai
) as base
on conflict (atraccion_id, nombre) do nothing;

update public.atracciones_imagenes ai
set carpeta_id = c.id,
    carpeta = c.nombre
from public.atracciones_carpetas c
where c.atraccion_id = ai.atraccion_id
  and c.nombre = coalesce(nullif(trim(ai.carpeta), ''), 'Sin carpeta');

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'atracciones_imagenes'
      and column_name = 'carpeta_id'
  ) then
    alter table public.atracciones_imagenes
      alter column carpeta_id set not null;
  end if;
end $$;

alter table public.atracciones_carpetas enable row level security;

drop policy if exists atracciones_carpetas_select_all on public.atracciones_carpetas;
create policy atracciones_carpetas_select_all
  on public.atracciones_carpetas
  for select
  to anon, authenticated
  using (true);

drop policy if exists atracciones_carpetas_insert_all on public.atracciones_carpetas;
create policy atracciones_carpetas_insert_all
  on public.atracciones_carpetas
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists atracciones_carpetas_update_all on public.atracciones_carpetas;
create policy atracciones_carpetas_update_all
  on public.atracciones_carpetas
  for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists atracciones_carpetas_delete_all on public.atracciones_carpetas;
create policy atracciones_carpetas_delete_all
  on public.atracciones_carpetas
  for delete
  to anon, authenticated
  using (true);
