-- Los textos de las imágenes de fondo son contenido administrable y se
-- traducen en base de datos, igual que los demás catálogos públicos.
create table if not exists public.imagenes_fondo_traducciones (
  id bigint generated by default as identity primary key,
  imagen_fondo_id bigint not null references public.imagenes_fondo(id) on delete cascade,
  idioma_id bigint not null references public.idiomas(id),
  nombre_destino text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (imagen_fondo_id, idioma_id)
);

create or replace function public.set_imagenes_fondo_traducciones_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_imagenes_fondo_traducciones_updated_at
  on public.imagenes_fondo_traducciones;
create trigger set_imagenes_fondo_traducciones_updated_at
before update on public.imagenes_fondo_traducciones
for each row execute function public.set_imagenes_fondo_traducciones_updated_at();

-- Conserva los rótulos existentes como la versión base en español.
insert into public.imagenes_fondo_traducciones (imagen_fondo_id, idioma_id, nombre_destino)
select imagen.id, idioma.id, coalesce(imagen.nombre_destino, '')
from public.imagenes_fondo imagen
join public.idiomas idioma on idioma.codigo = 'es'
on conflict (imagen_fondo_id, idioma_id) do nothing;

grant select on public.imagenes_fondo_traducciones to anon, authenticated;
grant insert, update, delete on public.imagenes_fondo_traducciones to authenticated;
grant usage, select on sequence public.imagenes_fondo_traducciones_id_seq to authenticated;

alter table public.imagenes_fondo_traducciones enable row level security;

drop policy if exists imagenes_fondo_traducciones_public_read
  on public.imagenes_fondo_traducciones;
create policy imagenes_fondo_traducciones_public_read
  on public.imagenes_fondo_traducciones for select to anon, authenticated
  using (true);

drop policy if exists imagenes_fondo_traducciones_admin_insert
  on public.imagenes_fondo_traducciones;
create policy imagenes_fondo_traducciones_admin_insert
  on public.imagenes_fondo_traducciones for insert to authenticated
  with check ((select public.es_administrador_actual()));

drop policy if exists imagenes_fondo_traducciones_admin_update
  on public.imagenes_fondo_traducciones;
create policy imagenes_fondo_traducciones_admin_update
  on public.imagenes_fondo_traducciones for update to authenticated
  using ((select public.es_administrador_actual()))
  with check ((select public.es_administrador_actual()));

drop policy if exists imagenes_fondo_traducciones_admin_delete
  on public.imagenes_fondo_traducciones;
create policy imagenes_fondo_traducciones_admin_delete
  on public.imagenes_fondo_traducciones for delete to authenticated
  using ((select public.es_administrador_actual()));
