-- Clasificación interna y relevancia de los destinos del catálogo.

create table if not exists public.catalogo_tipos_turisticos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  slug text not null,
  orden integer not null default 0,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalogo_tipos_turisticos_nombre_unique unique (nombre),
  constraint catalogo_tipos_turisticos_slug_unique unique (slug),
  constraint catalogo_tipos_turisticos_orden_check check (orden >= 0)
);

create index if not exists catalogo_tipos_turisticos_activo_orden_idx
  on public.catalogo_tipos_turisticos (activo, orden, nombre);

alter table public.catalogo_destinos
  add column if not exists prioridad smallint not null default 2;

alter table public.catalogo_destinos
  drop constraint if exists catalogo_destinos_prioridad_check;

alter table public.catalogo_destinos
  add constraint catalogo_destinos_prioridad_check check (prioridad in (1, 2));

alter table public.catalogo_destinos
  add column if not exists tipo_turistico_id bigint references public.catalogo_tipos_turisticos(id) on delete restrict;

create index if not exists catalogo_destinos_activo_prioridad_nombre_idx
  on public.catalogo_destinos (activo, prioridad, nombre);

create index if not exists catalogo_destinos_tipo_turistico_id_idx
  on public.catalogo_destinos (tipo_turistico_id);

create or replace function public.set_catalogo_tipos_turisticos_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_catalogo_tipos_turisticos_updated_at on public.catalogo_tipos_turisticos;
create trigger set_catalogo_tipos_turisticos_updated_at
before update on public.catalogo_tipos_turisticos
for each row execute function public.set_catalogo_tipos_turisticos_updated_at();

alter table public.catalogo_tipos_turisticos enable row level security;

grant select on public.catalogo_tipos_turisticos to anon, authenticated;
grant insert, update, delete on public.catalogo_tipos_turisticos to authenticated;
grant usage, select on sequence public.catalogo_tipos_turisticos_id_seq to authenticated;
grant update (nombre, orden, activo, prioridad, tipo_turistico_id, imagen_destino, division_area_id) on public.catalogo_destinos to authenticated;

drop policy if exists catalogo_tipos_turisticos_select_all on public.catalogo_tipos_turisticos;
create policy catalogo_tipos_turisticos_select_all
  on public.catalogo_tipos_turisticos for select
  using (true);

drop policy if exists catalogo_tipos_turisticos_insert_admin on public.catalogo_tipos_turisticos;
create policy catalogo_tipos_turisticos_insert_admin
  on public.catalogo_tipos_turisticos for insert to authenticated
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid()) and p.role = 'admin'
    )
  );

drop policy if exists catalogo_tipos_turisticos_update_admin on public.catalogo_tipos_turisticos;
create policy catalogo_tipos_turisticos_update_admin
  on public.catalogo_tipos_turisticos for update to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid()) and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid()) and p.role = 'admin'
    )
  );

drop policy if exists catalogo_tipos_turisticos_delete_admin on public.catalogo_tipos_turisticos;
create policy catalogo_tipos_turisticos_delete_admin
  on public.catalogo_tipos_turisticos for delete to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid()) and p.role = 'admin'
    )
  );

drop policy if exists catalogo_destinos_update_admin on public.catalogo_destinos;
create policy catalogo_destinos_update_admin
  on public.catalogo_destinos for update to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid()) and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid()) and p.role = 'admin'
        and prioridad in (1, 2)
    )
  );

drop view if exists public.v_catalogo_nacionales_destinos_admin;
create view public.v_catalogo_nacionales_destinos_admin
with (security_invoker = true) as
select
  r.id as region_id,
  r.nombre as region_nombre,
  p.id as pais_id,
  p.nombre as pais_nombre,
  p.iso2 as pais_iso2,
  p.slug as pais_slug,
  d.id as division_area_id,
  d.nombre as division_area_nombre,
  d.slug as division_area_slug,
  cd.id as destino_id,
  cd.nombre as destino_nombre,
  lower(extensions.unaccent(cd.nombre)) as destino_nombre_normalizado,
  cd.slug as destino_slug,
  cd.orden as destino_orden,
  cd.prioridad as destino_prioridad,
  tt.id as tipo_turistico_id,
  tt.nombre as tipo_turistico_nombre,
  cd.imagen_destino,
  cd.activo
from public.catalogo_destinos cd
join public.divisiones_area d on d.id = cd.division_area_id
join public.paises p on p.id = d.pais_id
join public.regiones r on r.id = p.region_id
left join public.catalogo_tipos_turisticos tt on tt.id = cd.tipo_turistico_id
where p.iso2 = 'MX';

drop view if exists public.v_catalogo_internacional_destinos_admin;
create view public.v_catalogo_internacional_destinos_admin
with (security_invoker = true) as
select
  r.id as region_id,
  r.nombre as region_nombre,
  p.id as pais_id,
  p.nombre as pais_nombre,
  p.iso2 as pais_iso2,
  p.slug as pais_slug,
  d.id as division_area_id,
  d.nombre as division_area_nombre,
  d.slug as division_area_slug,
  cd.id as destino_id,
  cd.nombre as destino_nombre,
  lower(extensions.unaccent(cd.nombre)) as destino_nombre_normalizado,
  cd.slug as destino_slug,
  cd.orden as destino_orden,
  cd.prioridad as destino_prioridad,
  tt.id as tipo_turistico_id,
  tt.nombre as tipo_turistico_nombre,
  cd.imagen_destino,
  cd.activo
from public.catalogo_destinos cd
join public.divisiones_area d on d.id = cd.division_area_id
join public.paises p on p.id = d.pais_id
join public.regiones r on r.id = p.region_id
left join public.catalogo_tipos_turisticos tt on tt.id = cd.tipo_turistico_id
where p.iso2 <> 'MX';

grant select on public.v_catalogo_nacionales_destinos_admin to anon, authenticated;
grant select on public.v_catalogo_internacional_destinos_admin to anon, authenticated;
