-- Las actividades solo agrupan una galeria por tipo. El contenido editorial
-- pertenece a cada imagen, que es la unidad que se muestra en el carrusel.
create table if not exists public.atracciones_imagenes_traducciones (
  id bigint generated by default as identity primary key,
  atraccion_imagen_id bigint not null references public.atracciones_imagenes(id) on delete cascade,
  idioma_id bigint not null references public.idiomas(id),
  nombre text,
  descripcion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (atraccion_imagen_id, idioma_id)
);

create index if not exists atracciones_imagenes_traducciones_imagen_id_idx
  on public.atracciones_imagenes_traducciones (atraccion_imagen_id, idioma_id);

alter table public.atracciones_imagenes_traducciones enable row level security;

drop policy if exists atracciones_imagenes_traducciones_select_all on public.atracciones_imagenes_traducciones;
create policy atracciones_imagenes_traducciones_select_all
  on public.atracciones_imagenes_traducciones for select to anon, authenticated using (true);

drop policy if exists atracciones_imagenes_traducciones_insert_authenticated on public.atracciones_imagenes_traducciones;
create policy atracciones_imagenes_traducciones_insert_authenticated
  on public.atracciones_imagenes_traducciones for insert to authenticated with check (true);

drop policy if exists atracciones_imagenes_traducciones_update_authenticated on public.atracciones_imagenes_traducciones;
create policy atracciones_imagenes_traducciones_update_authenticated
  on public.atracciones_imagenes_traducciones for update to authenticated using (true) with check (true);

drop policy if exists atracciones_imagenes_traducciones_delete_authenticated on public.atracciones_imagenes_traducciones;
create policy atracciones_imagenes_traducciones_delete_authenticated
  on public.atracciones_imagenes_traducciones for delete to authenticated using (true);

-- Conserva el contenido que ya se capturo: cada imagen recibe el texto que
-- anteriormente compartia toda la actividad.
insert into public.atracciones_imagenes_traducciones (
  atraccion_imagen_id, idioma_id, nombre, descripcion
)
select ai.id, apt.idioma_id, apt.nombre, apt.descripcion
from public.atracciones_imagenes ai
join public.atracciones_principales_traducciones apt
  on apt.atracciones_principales_id = ai.atraccion_id
on conflict (atraccion_imagen_id, idioma_id) do nothing;

-- Una actividad es ahora una galería: varias imágenes pueden estar visibles
-- simultáneamente en el carrusel público.
drop index if exists public.atracciones_imagenes_unica_activa_por_atraccion;

-- Consolida actividades duplicadas en la mas antigua del mismo destino y tipo.
-- Primero replica las carpetas para poder conservar su organizacion al mover
-- las imagenes; despues borra los contenedores repetidos.
with duplicadas as (
  select id,
    min(id) over (partition by detalles_destino_id, catalogo_atraccion_id) as actividad_destino_id
  from public.atracciones_principales
  where catalogo_atraccion_id is not null
)
insert into public.atracciones_carpetas (atraccion_id, nombre, orden)
select d.actividad_destino_id, c.nombre, c.orden
from public.atracciones_carpetas c
join duplicadas d on d.id = c.atraccion_id
where d.id <> d.actividad_destino_id
on conflict (atraccion_id, nombre) do nothing;

with duplicadas as (
  select id,
    min(id) over (partition by detalles_destino_id, catalogo_atraccion_id) as actividad_destino_id
  from public.atracciones_principales
  where catalogo_atraccion_id is not null
), imagenes_a_mover as (
  select ai.id as imagen_id,
    d.actividad_destino_id,
    carpeta_destino.id as carpeta_destino_id,
    carpeta_destino.nombre as carpeta_destino_nombre
  from public.atracciones_imagenes ai
  join duplicadas d on d.id = ai.atraccion_id
  left join public.atracciones_carpetas carpeta_origen on carpeta_origen.id = ai.carpeta_id
  left join public.atracciones_carpetas carpeta_destino
    on carpeta_destino.atraccion_id = d.actividad_destino_id
   and carpeta_destino.nombre = carpeta_origen.nombre
  where d.id <> d.actividad_destino_id
)
update public.atracciones_imagenes ai
set atraccion_id = imagenes_a_mover.actividad_destino_id,
    carpeta_id = coalesce(imagenes_a_mover.carpeta_destino_id, ai.carpeta_id),
    carpeta = coalesce(imagenes_a_mover.carpeta_destino_nombre, ai.carpeta)
from imagenes_a_mover
where ai.id = imagenes_a_mover.imagen_id;

with duplicadas as (
  select id,
    min(id) over (partition by detalles_destino_id, catalogo_atraccion_id) as actividad_destino_id
  from public.atracciones_principales
  where catalogo_atraccion_id is not null
)
delete from public.atracciones_principales ap
using duplicadas d
where ap.id = d.id
  and d.id <> d.actividad_destino_id;

create unique index if not exists atracciones_principales_destino_tipo_unico
  on public.atracciones_principales (detalles_destino_id, catalogo_atraccion_id)
  where catalogo_atraccion_id is not null;
