-- Los nombres de pestañas viven en un catálogo único; cada hotel conserva su contenido.
create or replace function public.puede_editar_hoteles_actual()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and (
      p.role = 'admin' or exists (
        select 1 from public.roles r
        join public.role_permissions rp on rp.role_id = r.id
        join public.permissions permiso on permiso.id = rp.permission_id
        where r.key = p.role and permiso.key = 'hoteles.edit'
      )
    )
  );
$$;
grant execute on function public.puede_editar_hoteles_actual() to authenticated;

create table if not exists public.catalogo_pestanas_hotel (
  id bigint generated by default as identity primary key,
  titulo_es text not null check (length(btrim(titulo_es)) between 1 and 120),
  icono text not null default 'article' check (icono in ('article', 'schedule', 'local_offer', 'info', 'restaurant', 'star')),
  activo boolean not null default true
);

create unique index if not exists catalogo_pestanas_hotel_titulo_unico
  on public.catalogo_pestanas_hotel (lower(regexp_replace(btrim(titulo_es), '[[:space:]]+', ' ', 'g')));

create table if not exists public.catalogo_pestanas_hotel_traducciones (
  catalogo_pestana_id bigint not null references public.catalogo_pestanas_hotel(id) on delete cascade,
  idioma_id bigint not null references public.idiomas(id),
  titulo text not null check (length(btrim(titulo)) > 0),
  primary key (catalogo_pestana_id, idioma_id)
);

grant select on public.catalogo_pestanas_hotel, public.catalogo_pestanas_hotel_traducciones to anon, authenticated;
grant insert, update, delete on public.catalogo_pestanas_hotel, public.catalogo_pestanas_hotel_traducciones to authenticated;
alter table public.catalogo_pestanas_hotel enable row level security;
alter table public.catalogo_pestanas_hotel_traducciones enable row level security;

create policy catalogo_pestanas_hotel_read on public.catalogo_pestanas_hotel
  for select to anon, authenticated using (true);
create policy catalogo_pestanas_hotel_write on public.catalogo_pestanas_hotel
  for all to authenticated using ((select public.puede_editar_hoteles_actual()))
  with check ((select public.puede_editar_hoteles_actual()));
create policy catalogo_pestanas_hotel_traducciones_read on public.catalogo_pestanas_hotel_traducciones
  for select to anon, authenticated using (true);
create policy catalogo_pestanas_hotel_traducciones_write on public.catalogo_pestanas_hotel_traducciones
  for all to authenticated using ((select public.puede_editar_hoteles_actual()))
  with check ((select public.puede_editar_hoteles_actual()));

drop policy if exists hotel_detalle_secciones_admin_read on public.hotel_detalle_secciones;
create policy hotel_detalle_secciones_admin_read on public.hotel_detalle_secciones
  for select to authenticated using ((select public.puede_editar_hoteles_actual()));
drop policy if exists hotel_detalle_secciones_write on public.hotel_detalle_secciones;
create policy hotel_detalle_secciones_write on public.hotel_detalle_secciones
  for all to authenticated using ((select public.puede_editar_hoteles_actual()))
  with check ((select public.puede_editar_hoteles_actual()));
drop policy if exists hotel_detalle_traducciones_write on public.hotel_detalle_secciones_traducciones;
create policy hotel_detalle_traducciones_write on public.hotel_detalle_secciones_traducciones
  for all to authenticated using ((select public.puede_editar_hoteles_actual()))
  with check ((select public.puede_editar_hoteles_actual()));

insert into public.catalogo_pestanas_hotel (titulo_es, icono)
values ('Plan Todo Incluido', 'local_offer'), ('Check-in / Horarios', 'schedule')
on conflict do nothing;

-- Vincular títulos ya guardados, incluidas las traducciones. No se altera su contenido.
insert into public.catalogo_pestanas_hotel (titulo_es, icono)
select distinct on (lower(regexp_replace(btrim(t.titulo), '[[:space:]]+', ' ', 'g')))
  btrim(t.titulo), s.icono
from public.hotel_detalle_secciones s
join public.hotel_detalle_secciones_traducciones t on t.seccion_id = s.id and t.idioma_id = 1
where not exists (
  select 1 from public.catalogo_pestanas_hotel c
  where lower(regexp_replace(btrim(c.titulo_es), '[[:space:]]+', ' ', 'g')) =
    lower(regexp_replace(btrim(t.titulo), '[[:space:]]+', ' ', 'g'))
)
order by lower(regexp_replace(btrim(t.titulo), '[[:space:]]+', ' ', 'g')), s.id
on conflict do nothing;

insert into public.catalogo_pestanas_hotel_traducciones (catalogo_pestana_id, idioma_id, titulo)
select distinct on (c.id, t.idioma_id) c.id, t.idioma_id, t.titulo
from public.hotel_detalle_secciones s
join public.hotel_detalle_secciones_traducciones es on es.seccion_id = s.id and es.idioma_id = 1
join public.hotel_detalle_secciones_traducciones t on t.seccion_id = s.id
join public.catalogo_pestanas_hotel c on lower(regexp_replace(btrim(c.titulo_es), '[[:space:]]+', ' ', 'g')) =
  lower(regexp_replace(btrim(es.titulo), '[[:space:]]+', ' ', 'g'))
order by c.id, t.idioma_id, s.id
on conflict do nothing;

alter table public.hotel_detalle_secciones
  add column if not exists catalogo_pestana_id bigint references public.catalogo_pestanas_hotel(id);

update public.hotel_detalle_secciones s
set catalogo_pestana_id = c.id
from public.hotel_detalle_secciones_traducciones t, public.catalogo_pestanas_hotel c
where t.seccion_id = s.id and t.idioma_id = 1
  and lower(regexp_replace(btrim(t.titulo), '[[:space:]]+', ' ', 'g')) =
    lower(regexp_replace(btrim(c.titulo_es), '[[:space:]]+', ' ', 'g'))
  and s.catalogo_pestana_id is null;

do $$ begin
  if exists (select 1 from public.hotel_detalle_secciones where catalogo_pestana_id is null) then
    raise exception 'Hay pestañas sin título en español; corrígelas antes de vincular el catálogo';
  end if;
  if exists (
    select 1 from public.hotel_detalle_secciones
    group by hotel_id, catalogo_pestana_id having count(*) > 1
  ) then
    raise exception 'Hay pestañas duplicadas en un mismo hotel; revísalas antes de aplicar el catálogo';
  end if;
end $$;

alter table public.hotel_detalle_secciones alter column catalogo_pestana_id set not null;
create unique index if not exists hotel_detalle_secciones_catalogo_por_hotel
  on public.hotel_detalle_secciones (hotel_id, catalogo_pestana_id);

-- El título se obtiene siempre del catálogo; únicamente el contenido varía por hotel.
alter table public.hotel_detalle_secciones_traducciones drop column titulo;

-- Guardar nombre, icono y traducciones como una sola operación.
create or replace function public.guardar_catalogo_pestana_hotel(
  p_id bigint, p_titulo_es text, p_icono text, p_activo boolean, p_traducciones jsonb
)
returns bigint language plpgsql security invoker set search_path = public as $$
declare
  v_id bigint;
  traduccion jsonb;
begin
  if not (select public.puede_editar_hoteles_actual()) then raise exception 'No autorizado'; end if;
  if p_titulo_es is null or length(btrim(p_titulo_es)) not between 1 and 120 then
    raise exception 'Nombre de pestaña inválido';
  end if;
  if jsonb_typeof(p_traducciones) is distinct from 'array' then
    raise exception 'Traducciones inválidas';
  end if;

  if p_id is null then
    insert into public.catalogo_pestanas_hotel (titulo_es, icono, activo)
    values (p_titulo_es, p_icono, p_activo) returning id into v_id;
  else
    update public.catalogo_pestanas_hotel
    set titulo_es = p_titulo_es, icono = p_icono, activo = p_activo
    where id = p_id returning id into v_id;
    if v_id is null then raise exception 'Pestaña no encontrada'; end if;
  end if;

  for traduccion in select value from jsonb_array_elements(p_traducciones) loop
    insert into public.catalogo_pestanas_hotel_traducciones (catalogo_pestana_id, idioma_id, titulo)
    values (v_id, (traduccion->>'idioma_id')::bigint, traduccion->>'titulo')
    on conflict (catalogo_pestana_id, idioma_id) do update set titulo = excluded.titulo;
  end loop;
  return v_id;
end;
$$;
revoke all on function public.guardar_catalogo_pestana_hotel(bigint, text, text, boolean, jsonb) from public;
grant execute on function public.guardar_catalogo_pestana_hotel(bigint, text, text, boolean, jsonb) to authenticated;

create or replace function public.guardar_hotel_detalle_secciones(p_hotel_id bigint, p_secciones jsonb)
returns void language plpgsql security invoker set search_path = public as $$
declare
  seccion jsonb;
  traduccion jsonb;
  v_seccion_id uuid;
  v_catalogo_id bigint;
  ids uuid[] := '{}'::uuid[];
  catalogos bigint[] := '{}'::bigint[];
begin
  if not (select public.puede_editar_hoteles_actual()) then raise exception 'No autorizado'; end if;
  if jsonb_typeof(p_secciones) is distinct from 'array' then raise exception 'Secciones invalidas'; end if;

  -- Quitar primero las pestañas descartadas para liberar su opción de catálogo.
  delete from public.hotel_detalle_secciones where hotel_id = p_hotel_id
    and not (id = any(array(select (value->>'id')::uuid from jsonb_array_elements(p_secciones))));

  for seccion in select value from jsonb_array_elements(p_secciones) loop
    v_seccion_id := (seccion->>'id')::uuid;
    v_catalogo_id := (seccion->>'catalogo_pestana_id')::bigint;
    if v_seccion_id = any(ids) or v_catalogo_id = any(catalogos) then
      raise exception 'Pestaña duplicada en el hotel';
    end if;
    if not exists (select 1 from public.catalogo_pestanas_hotel where id = v_catalogo_id) then
      raise exception 'Selecciona una pestaña del catálogo';
    end if;
    if exists (select 1 from public.hotel_detalle_secciones where id = v_seccion_id and hotel_id <> p_hotel_id) then
      raise exception 'La seccion pertenece a otro hotel';
    end if;
    ids := array_append(ids, v_seccion_id);
    catalogos := array_append(catalogos, v_catalogo_id);

    if exists (select 1 from public.hotel_detalle_secciones
      where hotel_id = p_hotel_id and catalogo_pestana_id = v_catalogo_id and id <> v_seccion_id) then
      raise exception 'Pestaña duplicada en el hotel';
    end if;
    insert into public.hotel_detalle_secciones (id, hotel_id, catalogo_pestana_id, orden, icono, visible)
    select v_seccion_id, p_hotel_id, v_catalogo_id, (seccion->>'orden')::integer, c.icono,
      (seccion->>'visible')::boolean from public.catalogo_pestanas_hotel c where c.id = v_catalogo_id
    on conflict (id) do update set catalogo_pestana_id = excluded.catalogo_pestana_id,
      orden = excluded.orden, icono = excluded.icono, visible = excluded.visible;

    for traduccion in select value from jsonb_array_elements(seccion->'traducciones') loop
      insert into public.hotel_detalle_secciones_traducciones
        (seccion_id, idioma_id, contenido_html, bloques)
      values (v_seccion_id, (traduccion->>'idioma_id')::bigint,
        traduccion->>'contenido_html', traduccion->'bloques')
      on conflict (seccion_id, idioma_id) do update set
        contenido_html = excluded.contenido_html, bloques = excluded.bloques;
    end loop;
  end loop;

  delete from public.hotel_detalle_secciones where hotel_id = p_hotel_id and not (id = any(ids));
end;
$$;

notify pgrst, 'reload schema';
