-- Los tipos turísticos son contenido público administrable, por lo que sus
-- traducciones se almacenan junto al catálogo y no en los archivos de UI.
create table if not exists public.catalogo_tipos_turisticos_traducciones (
  id bigint generated by default as identity primary key,
  tipo_turistico_id bigint not null references public.catalogo_tipos_turisticos(id) on delete cascade,
  idioma_id bigint not null references public.idiomas(id),
  nombre text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tipo_turistico_id, idioma_id)
);

create index if not exists catalogo_tipos_turisticos_traducciones_tipo_idioma_idx
  on public.catalogo_tipos_turisticos_traducciones (tipo_turistico_id, idioma_id);

create or replace function public.set_catalogo_tipos_turisticos_traducciones_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_catalogo_tipos_turisticos_traducciones_updated_at
  on public.catalogo_tipos_turisticos_traducciones;
create trigger set_catalogo_tipos_turisticos_traducciones_updated_at
before update on public.catalogo_tipos_turisticos_traducciones
for each row execute function public.set_catalogo_tipos_turisticos_traducciones_updated_at();

-- Inicializa el idioma base para que los catálogos existentes conserven su
-- contenido en español mientras se generan o capturan los demás idiomas.
insert into public.catalogo_tipos_turisticos_traducciones (tipo_turistico_id, idioma_id, nombre)
select tipo.id, idioma.id, tipo.nombre
from public.catalogo_tipos_turisticos tipo
join public.idiomas idioma on idioma.codigo = 'es'
on conflict (tipo_turistico_id, idioma_id) do nothing;

grant select on public.catalogo_tipos_turisticos_traducciones to anon, authenticated;
grant insert, update, delete on public.catalogo_tipos_turisticos_traducciones to authenticated;
grant usage, select on sequence public.catalogo_tipos_turisticos_traducciones_id_seq to authenticated;

alter table public.catalogo_tipos_turisticos_traducciones enable row level security;

drop policy if exists catalogo_tipos_turisticos_traducciones_select_all
  on public.catalogo_tipos_turisticos_traducciones;
create policy catalogo_tipos_turisticos_traducciones_select_all
  on public.catalogo_tipos_turisticos_traducciones for select to anon, authenticated
  using (true);

drop policy if exists catalogo_tipos_turisticos_traducciones_insert_admin
  on public.catalogo_tipos_turisticos_traducciones;
create policy catalogo_tipos_turisticos_traducciones_insert_admin
  on public.catalogo_tipos_turisticos_traducciones for insert to authenticated
  with check (
    exists (
      select 1 from public.profiles profile
      where profile.id = (select auth.uid()) and profile.role = 'admin'
    )
  );

drop policy if exists catalogo_tipos_turisticos_traducciones_update_admin
  on public.catalogo_tipos_turisticos_traducciones;
create policy catalogo_tipos_turisticos_traducciones_update_admin
  on public.catalogo_tipos_turisticos_traducciones for update to authenticated
  using (
    exists (
      select 1 from public.profiles profile
      where profile.id = (select auth.uid()) and profile.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles profile
      where profile.id = (select auth.uid()) and profile.role = 'admin'
    )
  );

drop policy if exists catalogo_tipos_turisticos_traducciones_delete_admin
  on public.catalogo_tipos_turisticos_traducciones;
create policy catalogo_tipos_turisticos_traducciones_delete_admin
  on public.catalogo_tipos_turisticos_traducciones for delete to authenticated
  using (
    exists (
      select 1 from public.profiles profile
      where profile.id = (select auth.uid()) and profile.role = 'admin'
    )
  );
